##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# `wraith capture capture.yaml`
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"
phantomjs_options: '--web-security=false --ignore-ssl-errors=true --ssl-protocol=tlsv1'

# (required) The domains to take screenshots of.
domains:
#  local:        "http://localhost:8080"
  integration:  "http://llc-integration-frontend.service.dev.ctp.local"
  preview:      "http://llc-preview-frontend.service.dev.ctp.local"

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
#  - 320
#  - 600x768
# - 768
- 1024
# - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
# before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '10%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 2

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: alphanumeric

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
 # Pages that don't require log in
  account-forgotten-password:
    path: /account/reset/forgottenpassword
  account-invalid-token:
    path: /account/reset/invalidtoken
  account-new-request:
    path: /account/reset/request
  app-error:
    path: /error
  app-page-not-found:
    path: /page-not-found
  app-login:
    path: /login
  app-logout:
    path: /logout
 # Pages that require you to be logged in
  app-home:
    path: /
    before_capture: 'javascript/login.js'
  maintain-search:
    path: /search
    before_capture: 'javascript/login.js'
  maintain-add-location:
    path: /add-land-charge/add-location
    before_capture: 'javascript/login.js'
  maintain-add-provisions:
    path: /add-land-charge/add-provisions
    before_capture: 'javascript/login.js'
  maintain-llc1-create-llc1:
    path: /create-llc1/location
    before_capture: 'javascript/login.js'
  admin-lr:
    path: /admin/land-registry
    before_capture: 'javascript/login.js'
  admin-add:
    path: /admin/user/add/role
    before_capture: 'javascript/login.js'
######################### WIP BELOW THIS LINE #####################
#  admin-search-results:
#    path: /admin/search-results
#    before_capture: 'javascript/login.js'
#  admin-view-user:
#    path:  /admin/user/view/la_admin1%40email.com
#    before_capture: 'javascript/login.js'
#  admin-add-user-details:
#    path: /admin/user/add/details
#    before_capture: 'javascript/login.js'
#  admin-add-user-confirm:
#    path: /admin/user/add/confirm-details
#    before_capture: 'javascript/login.js'
#  admin-add-summary:
#    path: /admin/user/summary
#    before_capture: 'javascript/login.js'
#  admin-edit-user-details:
#    path: /admin/user/edit/details
#    before_capture: 'javascript/login.js'
#  admin-edit-confirm-details:
#    path: /admin/user/edit/confirm-details
#    before_capture: 'javascript/login.js'
#  admin-edit-confirm-details:
#    path: /admin/user/view/la_admin1%40email.com?updated=True
#    before_capture: 'javascript/login.js'
#  add-land-charge:
#    path: /add-land-charge
#    before_capture: 'javascript/login.js'
#  add-more-information: /add-land-charge/more-information
#   add-additional-information: /add-land-charge/additional-info
#   add-charge-reason: /add-land-charge/charge-reason
#   add-charge-date: /add-land-charge/charge-date
#   add-expiry: /add-land-charge/expiry
#   add-confirmation: /add-land-charge/confirmation
#   view-land-charge: /view-land-charge/LLC-FCDPP
#   view-land-charge-history: /view-land-charge/LLC-FCDPP/history
#   modify-edit-charge-expiry: /modify-land-charge/LLC-FCDPP
#   modify-edit-provisions:	modify-land-charge/edit-provisions
#   modify-edit-location: /modify-land-charge/vary-location
#   modify-edit-additional-info: /modify-land-charge/additional-info
#   modify-edit-more-info: /modify-land-charge/more-information
#   modify-edit-charge-expiry: /modify-land-charge/expiry
#   modify-edit-charge-reason: /modify-land-charge/charge-reason
#   modify-edit-charge-date: /modify-land-charge/charge-date
#   modify-confirm:: /modify-land-charge/confirm
#   cancel-land-charge: /cancel-land-charge/LLC-FCDPP
#
#   search-llc1-extent-create:	/create-llc1/extent
#   search-llc1-extent-description: /create-llc1/description
#   search-llc1-extent-result: LC1 search result	/create-llc1/result
